wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.15
    framework: huggingface
    huggingface_version: 4.2.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.9
    t:
      1:
      - 1
      - 5
      - 11
      4: 3.7.9
      5: 0.10.15
      6: 4.2.2
codes_learning_rate:
  desc: null
  value: 1.0e-05
data_dir:
  desc: null
  value: /home/dc925/project/data/graphmimic/mortality/full_chunked
learning_rate:
  desc: null
  value: 1.0e-05
max_seq_length:
  desc: null
  value: 512
model_name_or_path:
  desc: null
  value: xhlu/electra-medal
num_train_epochs:
  desc: null
  value: 4
output_dir:
  desc: null
  value: /home/dc925/project/output/209/kge
task:
  desc: null
  value: mortality
threshold:
  desc: null
  value: 0.25
